# Site Settings
baseurl: ""
url : "https://kimsunsoo.github.io"

# Blog Settings
theme_settings :
  title : RoyEden Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Sunsoo Kim
    description : I make useful stuff. Fullstack Developer + Data analyst ðŸ˜†
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  s2034111@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: kimsunsoo
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
    site: royeden.netlify.com

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
